### ISSUE TITLE
网络切换，状态反应比较慢～

### ISSUE THREAD

**Issue by DaviAndorid** [sunyatas/NetStatusBus#1]
从无网状态切换到有网络状态，迟迟状态还是一样喔
![image](https://user-images.githubusercontent.com/13228580/58220731-96090d80-7d42-11e9-8e56-86d5c30476e6.png)

**Comment by sunyatas** [comment]
是发布的演示包的问题，我重新发布了一个，你把现在这个卸载了重新安装一下，https://www.pgyer.com/USYp
