### ISSUE TITLE
直接报错了

### ISSUE THREAD

**Issue by wlingf** [sunyatas/NetStatusBus#3]
<img width="922" alt="WX20190528-151705@2x" src="https://user-images.githubusercontent.com/19945512/58458644-51bfa800-815c-11e9-9863-5d7485ea9b70.png">
<img width="765" alt="WX20190528-151815@2x" src="https://user-images.githubusercontent.com/19945512/58458656-57b58900-815c-11e9-89c3-0f1db3bba909.png">

**Comment by wlingf** [comment]
使用该库，打包出来使用直接报错

**Comment by sunyatas** [comment]
不要在BaseActivity里面注册，建议在具体要用到的地方再注册

**Comment by wlingf** [comment]
我要时时的知道网络状态的切换，不是应该在baseActivity注册，总不能一个一个页面的去注册吧

**Comment by sunyatas** [comment]
0.1.5已修复该问题
